apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: pixelwar
type: Opaque
stringData:
  DB_HOST: db
  DB_PORT: "5432"
  DB_NAME: pixelwar
  DB_USER: pixelwar
  DB_PASSWORD: pixelwar2026!
  POSTGRES_DB: pixelwar
  POSTGRES_USER: pixelwar
  POSTGRES_PASSWORD: pixelwar2026!
